version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ["python", "test_app.py"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://telegram_bot:telegram_pass@db/telegram_bot_db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    restart: always
    networks:
      - bot-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=telegram_bot
      - POSTGRES_PASSWORD=telegram_pass
      - POSTGRES_DB=telegram_bot_db
    restart: always
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
